### ISSUE TITLE
Error: `ElegantCalendar.xcassets` doesn't exist

### ISSUE THREAD

**Issue by hungbv-0181** [ThasianX/ElegantCalendar#25]
I imported library by using Swift packages. After add ElegantCalendarView to view's body, I received fatalError at Image+Custom.swift file at line 9. I found that "uturn.left" image is already existed in ElegantCalendar.xcassets. please tell me how can I fix this?

**Comment by thrustToga** [comment]
You need to do this:

"Installation" in Readme. 

Inside whatever app is using ElegantCalendar or your Swift Package that uses ElegantCalendar as a dependency:

Scroll the project navigator down to the Swift Package Dependencies section. Inside ElegantCalendar, you'll see a directory called ElegantCalendar.xcassets.

After you've located it, open your project's settings and navigate to your target's build phases in a parallel window.

Drag ElegantCalendar.xcassets into your target's Copy Bundle Resources. Make sure that Copy items if needed is unticked and Create groups is ticked. This step is crucial because ElegantCalendar uses custom icons, which SPM will support in Swift 5.3.

This last step is for making sure that when others clone your repository, the assets will be available to them as well. Click the ElegantCalendar.xcassets that has appeared in your project navigator and in the inspector on the right, select Identity and Type. Inside, make sure that Location is set to Relative to Build Products.

**Comment by hungbv-0181** [comment]
@thrustToga thank you very much, It solved my problem
